"""Add blog_style to Content model

Revision ID: 23fb4635e457
Revises: c51f85bda39d
Create Date: 2025-07-09 13:45:19.785384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23fb4635e457'
down_revision = 'c51f85bda39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('email_subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_subject', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
