"""Add blog_style to Content model

Revision ID: 3a9763662b67
Revises: 23fb4635e457
Create Date: 2025-07-10 17:12:23.565099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9763662b67'
down_revision = '23fb4635e457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('key_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_page_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('landing_page_url')
        batch_op.drop_column('key_points')
        batch_op.drop_column('email_type')
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
