"""update

Revision ID: b730cdd4d7d5
Revises: 49a702126396
Create Date: 2025-07-14 17:07:35.321716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b730cdd4d7d5'
down_revision = '49a702126396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_purpose', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_style_tone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cut_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aspect_ratio_sns', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('other_requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generated_image_url', sa.String(length=2048), nullable=True))
        batch_op.alter_column('tone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('length_option',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('generated_text',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('generated_text',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('length_option',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('generated_image_url')
        batch_op.drop_column('other_requirements')
        batch_op.drop_column('aspect_ratio_sns')
        batch_op.drop_column('cut_count')
        batch_op.drop_column('brand_style_tone')
        batch_op.drop_column('product_category')
        batch_op.drop_column('ad_purpose')

    # ### end Alembic commands ###
