"""Add blog_style to Content model

Revision ID: c51f85bda39d
Revises: 5937274d13b4
Create Date: 2025-07-09 13:42:36.924474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51f85bda39d'
down_revision = '5937274d13b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_style', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('blog_style')

    # ### end Alembic commands ###
